# Generated by Django 3.2.2 on 2021-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_name_str',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='task_id_str',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
