# Generated by Django 3.2.2 on 2021-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20210801_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='group_name_str',
            new_name='group_name_del',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='task_id_str',
        ),
        migrations.AddField(
            model_name='notification',
            name='task_id_del',
            field=models.IntegerField(null=True),
        ),
    ]
