version: "3"

services:
  web:
    image: registry.gitlab.com/auditor2/production/wondertaskbackend:latest
    container_name: wondertask-backend
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:9007
    volumes:
      - /var/wondertask_media:code/media
    ports:
      - "9007:9007"
  redis:
    image: redis:6.2.4
    container_name: redis
  celery:
    container_name: celery
    image: registry.gitlab.com/auditor2/production/wondertaskbackend:latest
    command: celery -A django_celery worker --beat --scheduler django --loglevel=info
    depends_on:
      - redis
volumes:
  pgdata:
