version: "3"

services:
  web:
    image: registry.gitlab.com/auditor2/production/wondertaskbackend:latest
    container_name: wondertask-backend
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:9007
    ports:
      - "9007:9007"
volumes:
  pgdata:
