version: "3"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend

    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    build:
      context: ./wondertask
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:9007
    volumes:
      - ./wondertask:/code/
    ports:
      - "9007:9007"
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
      DEBUG: 'true'
      API_PG_USER: postgres
      API_PG_PASSWORD: postgres
      API_PG_DB: postgres
      API_PG_HOST: db
      API_PG_PORT: 5432
    depends_on:
      - db
  redis:
    image: redis:6.2.4
    container_name: redis
  celery:
    container_name: celery
    build:
      context: ./wondertask
    command: celery -A django_celery worker -l info
    volumes:
      - ./wondertask:/code/
    depends_on:
      - redis
      - db
    environment:
      environment:
        SECRET_KEY: bigsecretkey
        DJANGO_CONFIGURATION: Develop
        DJANGO_SETTINGS_MODULE:
        DEBUG: 'true'
        API_PG_USER: postgres
        API_PG_PASSWORD: postgres
        API_PG_DB: postgres
        API_PG_HOST: db
        API_PG_PORT: 5432

volumes:
  pgdata:
