post:
  summary: 'Add task in group'
  tags: ['Group']
  operationId: AddTaskGroup
  parameters:
    - name: id
      in: path
      required: true
      description: 'The group id'
      schema:
        type: integer
    - name: task_id
      in: path
      required: true
      description: 'The task id'
      schema:
        type: integer
  responses:
    '200':
      content:
      description: 'The task added in group'


