post:
  summary: 'Leave the group'
  tags: ['Group']
  operationId: LeaveTheGroup
  parameters:
    - name: id
      in: path
      required: true
      description: 'The group id'
      schema:
        type: integer
  responses:
    '200':
      content:
      description: 'You left the group!'