post:
  summary: "Remove members from group"
  tags: ['Group Invite/Accept']
  operationId: RemoveUsersFromGroup
  parameters:
    - name: id
      in: path
      required: true
      description: 'The group id'
      schema:
        type: integer

  requestBody:
    content:
      application/json:
        schema:
          - $ref: '#/components/schemas/Group'
        examples:
          Group:
            $ref: '#/components/examples/Group'
  responses:
    '200':
      content:
        application/json:
          schema:
            - $ref: '#/components/schemas/Group'
      description: 'Users removed from group!'
    '400':
      description: 'HTTP_400_BAD_REQUEST'
    '401':
      description: 'HTTP_401_UNAUTHORIZED'
    '403':
      description: 'HTTP_403_FORBIDDEN'




components:
  schemas:
    Group:
      type: object
      description: 'Group'
      properties:
        users_ids:
          type: array
          items:
            type: integer

  examples:
    Group:
      summary: 'Group'
      value:
        users_ids: [1, 3, 10]