get:
  summary: "Getting the list of groups"
  tags: ['Group']
  operationId: GetListGroups
  parameters: []
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GroupPagination'
      description: 'The list was got'
post:
  summary: "Creating a new group"
  tags: ['Group']
  operationId: CreateNewGroup
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          - $ref: '#/components/schemas/Group'
        examples:
          Group:
            $ref: '#/components/examples/Group'
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Group'
      description: 'The group was created'

components:
  schemas:
    GroupPagination:
      type: object
      description: 'Group'
      properties:
        count:
          type: integer
        next:
          type: string
        previous:
          type: string
        result:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              group_name:
                type: string
              is_system:
                type: string
              creator:
                type: integer
              count_open_tasks:
                type: integer
              group_members:
                type: array
                items:
                  type: integer
    Group:
      type: object
      description: 'Group'
      properties:
        id:
          type: integer
        group_name:
          type: string
        is_system:
          type: string
        creator:
          type: integer
        count_open_tasks:
          type: integer
        group_members:
          type: array
          items:
            type: integer

  examples:
    Group:
      summary: 'Group'
      value:
        group_name: 'Some group name'

