get:
  summary: "Getting the list of tags"
  tags: ['Tag']
  operationId: GetListTags
  parameters: []
  responses:
    '200':
      content:
        application/json:
          schema:
              $ref: '#/components/schemas/TagPagination'
      description: 'The list was got'
post:
  summary: "Creating a new tag"
  tags: ['Tag']
  operationId: CreateNewTag
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          - $ref: '#/components/schemas/Tag'
        examples:
          Tag:
            $ref: '#/components/examples/Tag'
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tag'
      description: 'The tag was created'

components:
  schemas:
    TagPagination:
      type: object
      description: 'TagPagination'
      properties:
        count:
          type: integer
        next:
          type: string
        previous:
          type: string
        result:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              user:
                type: integer
    Tag:
      type: object
      description: 'Tag'
      properties:
        id:
          type: integer
        name:
          type: string
        user:
          type: integer

  examples:
    Tag:
      summary: 'Tag'
      value:
        name: 'Some tag'
