post:
  summary: "Creating a new task in the group"
  tags: ['Tasks']
  operationId: CreateNewTask
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          - $ref: '#/components/schemas/Task'
        examples:
          Task:
            $ref: '#/components/examples/Task'
    description: '"Group" is id of choiced group. Field "group" may be == null. It means the task without a group". 
                 Required field is "title"' 
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '/static/docs/openapi/schema/response_single_task_1.yml#/components/schemas/SingleTask'
      description: 'The task was created'
get:
  summary: 'Getting the list of tasks with filtrations and sorting.'
  tags: ['Tasks']
  operationId: GetListTasks
  parameters:
    - name: tags
      in: query
      description: 'Filtering by tags'
      schema:
        type: string
    - name: search
      in: query
      description: 'Search in title field'
      schema:
        type: string
    - name: status
      in: query
      description: 'Filtering by status'
      schema:
        type: integer
    - name: priority
      in: query
      description: 'Filtering by priority'
      schema:
        type: integer
    - name: ordering
      in: query
      description: "Ordering by status, priority, creation_date, deadline, start_date, finish_date.
                    Example: +priority or -priority"
      schema:
        type: string
    - name: creation_date_after
      in: query
      description: "Filtering by creation date >= creation_date.
                    Format: 2020-06-01. similarly for fields: deadline, start_date, finish_date"
      schema:
        type: string
        format: date
    - name: creation_date_before
      in: query
      description: "Filtering by creation date <= creation_date.
                    Format: 2020-06-01. similarly for fields: deadline, start_date, finish_date"
      schema:
        type: string
        format: date
    - name: keyword
      in: query
      description: 'Filter by keyword. Keywords: creator, executor, observer, favorite, today, tomorrow, week, month'
      schema:
        type: string
    - name: status_first
      in: query
      description: 'Filter by status first. CREATED=0, IN_PROGRESS=1, IN_WAITING=2, DONE=4, OVERDUE=8
      IN_PROGRESS_OVERDUE=9, IN_WAITING_OVERDUE=10'
      schema:
        type: string


  responses:
    '200':
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                type: integer
              next:
                type: integer
              previous:
                type: integer
              favourite:
                type: integer
              deadline_today:
                type: integer
              results:
                type: array
                items:
                  $ref: '/static/docs/openapi/schema/response_single_task_1.yml#/components/schemas/SingleTask'
      description: 'The list was got'

components:
  schemas:
    Task:
      type: object
      description: 'Task'
      properties:
        title:
          type: string
        description:
          type: string
        group:
          type: integer
        deadline:
          type: string
        priority:
          type: integer
        parent:
          type: integer
        user_tags:
          type: array
          items:
            type: string

  examples:
    Task:
      summary: 'Task'
      value:
        title: Новая задача
        description: Описание
        group:
        deadline: '2021-05-13T01:00:59.502847Z'
        priority: 0
        parent: 
        user_tags: ['tag1', 'tag2', 'tag3']
