post:
  summary: "Add tags to task"
  tags: ['TaskTag']
  operationId: AddTagsToTask
  parameters:
    - name: task_id
      in: path
      required: true
      description: 'The task id'
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          tags:
            type: array
            items:
              type string
        examples:
          Tag:
            value:
              tags: ["project", "work"]
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '/static/docs/openapi/schema/response_single_task_1.yml#/components/schemas/SingleTask'
      description: 'The tags was added to task'
