get:
  summary: "Getting the list of comments level=0 only"
  tags: ["Comment"]
  operationId: GetListCommentsZeroLevel
  parameters:
    - name: task_id
      in: path
      required: true
      description: "The task id"
      schema:
        type: integer
  responses:
    "200":
      content:
        application/json:
          schema:
            type: array
            items:
              - $ref: "#/components/schemas/Comment"
          examples:
            Comment:
              $ref: "#/components/examples/Comment"
      description: "The list has been recieved"
post:
  summary: "Creating a new comment for the task"
  tags: ["Comment"]
  operationId: CreateNewComment
  parameters:
    - name: task_id
      in: path
      required: true
      description: "The task id"
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          - $ref: "#/components/schemas/Comment1"
        examples:
          Task:
            $ref: "#/components/examples/Comment1"
  responses:
    "201":
      content:
        application/json:
          schema:
            - $ref: "#/components/schemas/Comment"
          examples:
            Task:
              $ref: "#/components/examples/Comment"
      description: "Comment is created. The id is id of comment table here."

components:
  schemas:
    Comment:
      type: object
      description: "Comment"
      properties:
        id:
          type: integer
        author:
          type: object
          properties:
            url:
              type: string
            id:
              type: integer
            email:
              type: string
            full_name:
              type: string
            avatar_image:
              type: string
        task:
          type: integer
        text:
          type: string
        tree_id:
          type: integer
        level:
          type: integer
        parent:
          type: integer
        creation_date:
          type: string
    Comment1:
      type: object
      description: "Comment1"
      properties:
        author:
          type: object
          properties:
            url:
              type: string
            id:
              type: integer
            email:
              type: string
            full_name:
              type: string
            avatar_image:
              type: string
        text:
          type: string
        parent:
          type: integer

  examples:
    Comment:
      summary: "Comment"
      value:
        author: 
          url: "http://0.0.0.0:9007/v1/accounts/user/1/"
          id: 1
          email: "test@test.com"
          full_name: 'дон Педро'
          avatar_image: "http://0.0.0.0:9007/media/avatar_img/1_215f9b_Avatar.png"
        task: 1
        text: "comment text"
        tree_id: 1
        level: 0
        parent: null
        creation_date: "2021-06-18T18:40:00.000140+03:00"
    Comment1:
      summary: "Comment1"
      value:
        author: 
          url: "http://0.0.0.0:9007/v1/accounts/user/1/"
          id: 1
          email: "test@test.com"
          full_name: 'дон Педро'
          avatar_image: "http://0.0.0.0:9007/media/avatar_img/1_215f9b_Avatar.png"
        text: "comment text"
        parent: null
