post:
  summary: "Creating a new task"
  tags: ['Tasks']
  operationId: CreateNewTask
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          - $ref: '#/components/schemas/Task'
        examples:
          Task:
            $ref: '#/components/examples/Task'
    description: 'Creator is id of the user which create the task. Required fields are "title" and "creator"' 
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '/static/docs/openapi/schema/response_single_task.yml#/components/schemas/SingleTask'
      description: 'The task was created'
get:
  summary: 'Getting the list of tasks sorted descending by "creation_date"'
  tags: ['Tasks']
  operationId: GetListTasks
  parameters: []
  responses:
    '200':
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '/static/docs/openapi/schema/response_single_task.yml#/components/schemas/SingleTask'
      description: 'The list was got'

components:
  schemas:
    Task:
      type: object
      description: 'Task'
      properties:
        title:
          type: string
        deadline:
          type: string
        priority:
          type: integer
        creator:
          type: integer
        parent:
          type: integer

  examples:
    Task:
      summary: 'Task'
      value:
        title: Новая задача
        deadline: '2021-05-13T01:00:59.502847Z'
        priority: 0
        creator: 1
        parent: 0
