get:
  summary: 'Finish the task has id'
  tags: ['Tasks']
  operationId: FinishTask
  parameters:
    - name: id
      in: path
      required: true
      description: 'The task id'
      schema:
        type: integer
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '/static/docs/openapi/schema/response_single_task_4.yml#/components/schemas/SingleTask'
      description: 'The task finished'
      