post:
  summary: "Creating a new task in the group"
  tags: ['Tasks']
  operationId: CreateNewTask
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          - $ref: '#/components/schemas/Task'
        examples:
          Task:
            $ref: '#/components/examples/Task'
    description: '"Group" is id of choiced group. If "group"== null then group is created "FREE_TASKS". 
                 Required field is "title"' 
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '/static/docs/openapi/schema/response_single_task_1.yml#/components/schemas/SingleTask'
      description: 'The task was created'
get:
  summary: 'Getting the list of tasks with filtrations and sorting.'
  tags: ['Tasks']
  operationId: GetListTasks
  parameters:
    - name: search
      in: query
      description: 'Search in title field'
      schema:
        type: string
    - name: status
      in: query
      description: 'Filtering by status'
      schema:
        type: integer
    - name: priority
      in: query
      description: 'Filtering by priority'
      schema:
        type: integer
    - name: ordering
      in: query
      description: "Ordering by status, priority, creation_date, deadline, start_date, finish_date.
                    Example: +priority or -priority"
      schema:
        type: string
    - name: creation_date_after
      in: query
      description: "Filtering by creation date >= creation_date.
                    Format: 2020-06-01. similarly for fields: deadline, start_date, finish_date"
      schema:
        type: string
        format: date
    - name: creation_date_before
      in: query
      description: "Filtering by creation date <= creation_date.
                    Format: 2020-06-01. similarly for fields: deadline, start_date, finish_date"
      schema:
        type: string
        format: date


  responses:
    '200':
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                type: integer
              next:
                type: integer
              previous:
                type: integer
              results:
                type: array
                items:
                  $ref: '/static/docs/openapi/schema/response_single_task_1.yml#/components/schemas/SingleTask'
      description: 'The list was got'

components:
  schemas:
    Task:
      type: object
      description: 'Task'
      properties:
        title:
          type: string
        group:
          type: integer
        deadline:
          type: string
        priority:
          type: integer
        parent:
          type: integer

  examples:
    Task:
      summary: 'Task'
      value:
        title: Новая задача
        group:
        deadline: '2021-05-13T01:00:59.502847Z'
        priority: 0
        parent: 
