get:
  summary: 'Getting the list of tasks of current user with filtration and sorting.'
  tags: ['Tasks']
  operationId: GetListMyTasks
  parameters:
    - name: search
      in: query
      description: 'Search in title field'
      schema:
        type: string
    - name: status
      in: query
      description: 'Filtering by status'
      schema:
        type: integer
    - name: priority
      in: query
      description: 'Filtering by priority'
      schema:
        type: integer
    - name: ordering
      in: query
      description: "Ordering by status, priority, creation_date, deadline, start_date, finish_date.
                    Example: +priority or -priority"
      schema:
        type: string
    - name: creation_date_after
      in: query
      description: "Filtering by creation date >= creation_date.
                    Format: 2020-06-01. similarly for fields: deadline, start_date, finish_date"
      schema:
        type: string
        format: date
    - name: creation_date_before
      in: query
      description: "Filtering by creation date <= creation_date.
                    Format: 2020-06-01. similarly for fields: deadline, start_date, finish_date"
      schema:
        type: string
        format: date


  responses:
    '200':
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                type: integer
              next:
                type: integer
              previous:
                type: integer
              results:
                type: array
                items:
                  $ref: '/static/docs/openapi/schema/response_single_task_1.yml#/components/schemas/SingleTask'
      description: 'The list was got'
    '401':
      description: Not authenticated
    '403':
      description: Access token does not have the required scope


components:
  schemas:
    Task:
      type: object
      description: 'Task'
      properties:
        title:
          type: string
        deadline:
          type: string
        priority:
          type: integer
        creator:
          type: integer
        parent:
          type: integer

  examples:
    Task:
      summary: 'Task'
      value:
        title: Новая задача
        deadline: '2021-05-13T01:00:59.502847Z'
        priority: 0
        creator: 1
        parent: 0
