get:
  summary: 'Getting the list of tasks have level=0 only and sorted descending by "creation_date"'
  tags: ['TaskTree']
  operationId: GetListTasksZeroLevel
  parameters: []
  responses:
    '200':
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '/static/docs/openapi/schema/response_single_task.yml#/components/schemas/SingleTask'
      description: 'The list was got'