get:
  summary: "Getting the list of docs for the comment id"
  tags: ["CommentDoc"]
  operationId: GetListCommentDocs
  parameters:
    - name: task_id
      in: path
      required: true
      description: "The task id"
      schema:
        type: integer
    - name: comment_id
      in: path
      required: true
      description: "The comment id"
      schema:
        type: integer
  responses:
    "200":
      content:
        application/json:
          schema:
            type: array
            items:
              - $ref: "#/components/schemas/Doc"
          examples:
            Comment:
              $ref: "#/components/examples/Doc"
      description: "The list has been recieved"
post:
  summary: "Creating a new doc for the comment"
  tags: ["CommentDoc"]
  operationId: CreateNewCommentDoc
  parameters:
    - name: task_id
      in: path
      required: true
      description: "The task id"
      schema:
        type: integer
    - name: comment_id
      in: path
      required: true
      description: "The comment id"
      schema:
        type: integer
  requestBody:
    content:
      multipart/form-data:
        schema:
          type: object
          properties:
            doc_file:
              type: string
              format: binary
          required:
            - doc_file
  responses:
    "201":
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 2
              task:
                type: integer
                example: 2
              comment:
                type: integer
                example: null
              doc_file:
                type: string
                example: "test text_file"
      description: "Doc is created. The id is id of doc table here."

components:
  schemas:
    Doc:
      type: object
      description: "Doc"
      properties:
        id:
          type: integer
        task:
          type: integer
        comment:
          type: integer
        doc_file:
          type: string

  examples:
    Doc:
      summary: "Doc"
      value:
        id: 1
        task: 1
        comment: 1
        doc_file: "Test File"
