openapi: 3.0.2
info:
  title: "API"
  version: "v1"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

security:
  - ApiKeyAuth: []

paths:
  # Accounts
  /v1/accounts/registration/:
    $ref: "./view/accounts/user_registration.yml"
  /v1/accounts/user/{user_id}/tags/:
    $ref: "./view/accounts/user_id_tags.yml"
  /v1/accounts/user/:
    $ref: "./view/accounts/user.yml"
  /v1/accounts/user/{user_id}/:
    $ref: "./view/accounts/user_id_1.yml"
  /v1/accounts/user/{user_id}/del-avatar/:
    $ref: "./view/accounts/user_id_del_avatar.yml"

  # Authentication
  /v1/authentication/token/obtaining/:
    $ref: "./view/accounts/obtaining.yml"
  /v1/authentication/token/refreshing/:
    $ref: "./view/accounts/refreshing.yml"
  /v1/authentication/token/verification/:
    $ref: "./view/accounts/verification.yml"

  # Task
  /v1/tasks/task/:
    $ref: "./view/tasks/task.yml"
  /v1/tasks/task/my/:
    $ref: "./view/tasks/task_my.yml"
  /v1/tasks/task/{id}/:
    $ref: "./view/tasks/task_id.yml"

  # Tasktree
  /v1/tasks/tasktree/:
    $ref: "./view/tasks/task_tree.yml"
  /v1/tasks/tasktree/{id}/:
    $ref: "./view/tasks/task_tree_id.yml"

  # Executor
  /v1/tasks/task/{task_id}/executors/:
    $ref: "./view/tasks/task_id_executors1.yml"
  /v1/tasks/task/{task_id}/executors/{pk}:
    $ref: "./view/tasks/task_id_executors_pk.yml"

  # Observer
  /v1/tasks/task/{task_id}/observers/:
    $ref: "./view/tasks/task_id_observers.yml"
  /v1/tasks/task/{task_id}/observers/{pk}/:
    $ref: "./view/tasks/task_id_observers_pk.yml"

  # Comment
  /v1/tasks/task/{task_id}/comment/:
    $ref: "./view/tasks/task_id_comment.yml"
  /v1/tasks/task/{task_id}/comment/{pk}/:
    $ref: "./view/tasks/task_id_comment_pk.yml"

  # Doc
  /v1/tasks/task/{task_id}/doc/:
    $ref: "./view/tasks/task_id_doc.yml"
  /v1/tasks/task/{task_id}/doc/{pk}/:
    $ref: "./view/tasks/task_id_doc_pk.yml"
  /v1/tasks/task/{task_id}/comment/{comment_id}/doc/:
    $ref: "./view/tasks/task_id_comment_id_doc.yml"
  /v1/tasks/task/{task_id}/comment/{comment_id}/doc/{pk}/:
    $ref: "./view/tasks/task_id_comment_id_doc_pk.yml"

  # Image
  /v1/tasks/task/{task_id}/image/:
    $ref: "./view/tasks/task_id_image.yml"
  /v1/tasks/task/{task_id}/image/{pk}/:
    $ref: "./view/tasks/task_id_image_pk.yml"
  /v1/tasks/task/{task_id}/comment/{comment_id}/image/:
    $ref: "./view/tasks/task_id_comment_id_image.yml"
  /v1/tasks/task/{task_id}/comment/{comment_id}/image/{pk}/:
    $ref: "./view/tasks/task_id_comment_id_image_pk.yml"

  # Audio
  /v1/tasks/task/{task_id}/audio/:
    $ref: "./view/tasks/task_id_audio.yml"
  /v1/tasks/task/{task_id}/audio/{pk}/:
    $ref: "./view/tasks/task_id_audio_pk.yml"
  /v1/tasks/task/{task_id}/comment/{comment_id}/audio/:
    $ref: "./view/tasks/task_id_comment_id_audio.yml"
  /v1/tasks/task/{task_id}/comment/{comment_id}/audio/{pk}/:
    $ref: "./view/tasks/task_id_comment_id_audio_pk.yml"

  # Tag
  /v1/tasks/tags/:
    $ref: "./view/tasks/tag.yml"
  /v1/tasks/tags/{id}/:
    $ref: "./view/tasks/tag_id.yml"

  # TaskTag
  /v1/tasks/task/{task_id}/add-tags/:
    $ref: "./view/tasks/task_id_tag_add.yml"
  /v1/tasks/task/{task_id}/del-tags/:
    $ref: "./view/tasks/task_id_tag_del.yml"

  # Group
  /v1/tasks/groups/:
    $ref: "./view/tasks/group.yml"
  /v1/tasks/groups/{id}/:
    $ref: "./view/tasks/group_id.yml"

  # Group Invite/Accept
  /v1/tasks/groups/{id}/invite/:
    $ref: "./view/tasks/group_invite.yml"
  /v1/tasks/groups/{id}/accept-invite/:
    $ref: "./view/tasks/group_accept.yml"