# Generated by Django 3.2.2 on 2021-06-07 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='system_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='sum_elapsed_time',
        ),
        migrations.AddField(
            model_name='task',
            name='sum_elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.DeleteModel(
            name='TaskSystemTags',
        ),
    ]
