# Generated by Django 3.2.2 on 2021-06-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_auto_20210615_1412'),
        ('tasks', '0002_auto_20210607_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='clocked_shedule',
            field=models.ManyToManyField(to='django_celery_beat.ClockedSchedule'),
        ),
        migrations.AddField(
            model_name='task',
            name='periodic_tasks',
            field=models.ManyToManyField(related_name='deadline_periiodic', to='django_celery_beat.PeriodicTask'),
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_times', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of times execution of the interval')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date the last execution of the interval')),
                ('crontab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
                ('periodic_tasks', models.ManyToManyField(to='django_celery_beat.PeriodicTask')),
                ('repeated_tasks', models.ManyToManyField(related_name='repeated_tasks', to='tasks.Task')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
