# Generated by Django 3.2.2 on 2021-08-16 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_comment_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationInGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_multiple', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When was the token generated')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='The User which is associated to this invitation token')),
            ],
        ),
    ]
