# Generated by Django 3.2.2 on 2021-08-20 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_invitationingroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationingroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.group', verbose_name='The group to which invited'),
        ),
        migrations.AlterField(
            model_name='invitationingroup',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Multiple invitation'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
