# Generated by Django 3.2.2 on 2021-08-25 09:10

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210820_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('filesave_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.filesave')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=tasks.models.Video.video_directory_path)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tasks.comment')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tasks.task')),
            ],
            options={
                'db_table': 'video',
            },
            bases=('tasks.filesave',),
        ),
    ]
