# Generated by Django 3.2.2 on 2021-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_invitationingroup_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
